# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('internal_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('external_salary', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percentage_used', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_date', models.DateField()),
                ('time_use', models.IntegerField()),
                ('isExternal', models.BooleanField()),
                ('month_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('change', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('activation_key', models.CharField(max_length=300)),
                ('user_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('NM', 'NormalUser'), ('ITADMIN', 'ITAdministrator')], default='NM', max_length=20)),
                ('permission_description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PWP_num', models.CharField(max_length=20)),
                ('project_description', models.CharField(blank=True, default='', max_length=200)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_internal', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('business_manager', models.CharField(blank=True, default='', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expense_description', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('T', 'Travel'), ('S', 'Subcontractor'), ('E', 'Equipment'), ('O', 'Others')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employee_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(null=True)),
                ('internal_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('external_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorate', to='SEI.Employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageer', to='SEI.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Team'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeemonth',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Team'),
        ),
        migrations.AddField(
            model_name='chargestring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Project'),
        ),
    ]
