# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('activation_key', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('internal_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('external_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_internal', models.BooleanField()),
                ('isActive', models.BooleanField(default=True)),
                ('user_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('NM', 'NormalUser')], max_length=20)),
                ('permission_description', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, max_length=4)),
                ('month', models.CharField(max_length=30)),
                ('percentage_used', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('time_use', models.IntegerField()),
                ('month_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isExternal', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True)),
                ('change', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('PWP_num', models.CharField(max_length=20)),
                ('project_description', models.CharField(blank=True, default='', max_length=200)),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_internal', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Client')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expense_description', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('T', 'Travel'), ('S', 'Subcontractor'), ('E', 'Equipment'), ('O', 'Others')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)], default=2016, max_length=4)),
                ('month', models.CharField(max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(null=True)),
                ('internal_salary', models.FloatField()),
                ('external_salary', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorate', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manageer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='project_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.ProjectMonth'),
        ),
        migrations.AddField(
            model_name='employeelist',
            name='project_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.ProjectMonth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Team'),
        ),
        migrations.AddField(
            model_name='chargestring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Project'),
        ),
    ]
