# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('0', 'director'), ('1', 'manager'), ('2', 'employee')], max_length=1)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
