# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_spending',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SEI.Team'),
        ),
    ]
