# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SEI.Team'),
        ),
        migrations.AlterField(
            model_name='projectmonth',
            name='employee_list',
            field=models.ManyToManyField(related_name='do_project_this_month', to='SEI.Employee'),
        ),
    ]
