# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='permission_description',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='chargestring',
            name='date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=b'', max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_description',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[(b'ADMIN', b'Administrator'), (b'NM', b'NormalUser'), (b'ITADMIN', b'ITAdministrator')], default=b'NM', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargestring',
            name='charge',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee'),
        ),
        migrations.AlterField(
            model_name='employeemonth',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='business_manager',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='projectmonth',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.RemoveField(
            model_name='projectmonth',
            name='employee_list',
        ),
        migrations.AddField(
            model_name='projectmonth',
            name='employee_list',
            field=models.ManyToManyField(related_name='do_project_this_month', to='SEI.Employee'),
        ),
        migrations.AlterField(
            model_name='projectmonth',
            name='project_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEI.Employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorate', to='SEI.Employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageer', to='SEI.Employee'),
        ),
    ]
