# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
