# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0002_auto_20161126_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='client_name',
        ),
    ]
