# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0002_auto_20161117_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemonth',
            name='isExternal',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='employeemonth',
            name='month_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='employeemonth',
            name='time_use',
            field=models.IntegerField(null=True),
        ),
    ]
