# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0002_auto_20161128_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_uid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
