# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0003_remove_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_spending',
        ),
    ]
