# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0003_auto_20161117_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeavailability',
            name='percentage_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='projectmonth',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='projectmonth',
            name='employee_list',
            field=models.ManyToManyField(null=True, related_name='do_project_this_month', to='SEI.Employee'),
        ),
    ]
