# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0003_employee_employee_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryhistory',
            options={'get_latest_by': 'effective_from'},
        ),
    ]
