# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0005_auto_20161126_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargestring',
            name='charge',
        ),
        migrations.AddField(
            model_name='chargestring',
            name='charge_string',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SEI.Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_budget',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SEI.Team'),
        ),
    ]
