# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEI', '0006_auto_20161126_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
